Feature/43 - Upload Dialog UI for local and external datasets
MetaCell/sds-viewer pull request #46
Opened 2021-06-30 15:06 UTC by vidhya-metacell

2021-07-01 18:31 UTC, zsinnema requested changes

2021-07-01 18:31 UTC, zsinnema commented on src/utils/filesHandler.js
>              onDownloadProgress: (progressEvent) => {
please add the progress update here too

2021-07-01 18:31 UTC, zsinnema commented on src/utils/filesHandler.js
>          const PROXY_URL = 'https://cors-anywhere.herokuapp.com/';
remove this const (PROXY_URL)
not needed anymore since the cors headers are correct now

2021-07-01 18:31 UTC, zsinnema commented on src/utils/filesHandler.js
> +        axios.get(PROXY_URL, {
use the `url` parameter as the source, not the PROXY_URL

2021-07-02 06:01 UTC, zsinnema commented on src/utils/filesHandler.js
>              onDownloadProgress: (progressEvent) => {
@jrmartin what do you think? In the designs of Paul the upload from url has a different ui than the upload from local
why is it different? (not showing the progress)

2021-07-05 23:57 UTC, jrmartin commented on src/utils/filesHandler.js
>              onDownloadProgress: (progressEvent) => {
@zsinnema The difference between the local and url dataset loading happens because the user can load multiple local files but only one URL at a time. For the URL case, the user is shown a Loader icon while the dataset is loading, then the user is displayed a 'Done' button, which I think it works for this use case since user only loads one URL at a time.

2021-07-06 00:50 UTC, tgbugs commented on src/utils/filesHandler.js
>              onDownloadProgress: (progressEvent) => {
At some point being able to load multiple files in a single operation will be useful, but I'm not sure that this interface is the place it should happen.

2021-07-06 05:38 UTC, zsinnema commented on src/utils/filesHandler.js
>              onDownloadProgress: (progressEvent) => {
okay for now clear. thank @jrmartin @tgbugs

2021-07-06 05:39 UTC, zsinnema approved these changes

2021-07-06 05:39 UTC, merged