Graph builder
MetaCell/sds-viewer pull request #67
Opened 2021-08-03 14:22 UTC by ddelpiano

- Internal types model
- Splinter module to build the graph
- minor changes to react components

2021-08-05 08:13 UTC, zsinnema requested changes

2021-08-05 08:13 UTC, zsinnema commented on src/utils/Splinter.js
> +            if (this.nodes[key].type === typesModel.NamedIndividual.dataset.type) {
I would create a separate func. for getting the dataset node from the node list
same for the ontology
and then get them outside the loop
now you are mixing 2 different types of logic in one loop which makes it more difficult to 
1. test
2. read

it

something like this:
```
const getFirstNodeOfType = (nodeType) => this.nodes.find((node) => node.type === nodeType)
```

2021-08-05 08:13 UTC, zsinnema commented on src/utils/Splinter.js
> +        let temp_edges = this.edges.map(link => {
const

2021-08-05 08:13 UTC, zsinnema commented on src/utils/Splinter.js
> +        let temp_edges = this.edges.map(link => {
or even better: this.edges =

2021-08-05 08:13 UTC, zsinnema commented on src/utils/Splinter.js
> +        let subjects = {
const?

2021-08-05 08:13 UTC, zsinnema commented on src/utils/Splinter.js
> +        let protocols = {
const

2021-08-05 08:13 UTC, zsinnema commented on src/utils/Splinter.js
> +        let contributors = {
const

2021-08-05 08:13 UTC, zsinnema commented on src/utils/Splinter.js
> +                console.log("test");
test?

2021-08-05 08:13 UTC, zsinnema commented on src/utils/nodesFactory.js
> +        if (node.type === "Collection") {
use switch

2021-08-05 08:13 UTC, zsinnema commented on src/utils/nodesFactory.js
> +const Collection = function (node) {
why not use arrow function?

2021-08-05 18:35 UTC, ddelpiano commented on src/utils/Splinter.js
>              for (const key in this.nodes) {
I did few more changes, converted the js object to Map since I am using as a Map and I would like to avoid default keys of the object to collide with the logic in place for the graph.

2021-08-13 14:08 UTC, ddelpiano commented on src/utils/Splinter.js
>              let prefixCallback = function (prefix, iri) {
done in feature/66

2021-08-13 14:09 UTC, ddelpiano commented on src/utils/Splinter.js
> +        let typeFound = {
done in feature/66

2021-08-13 14:11 UTC, ddelpiano commented on src/utils/Splinter.js
> +                    found = false;
moved to a Map in feature/66

2021-08-13 14:13 UTC, ddelpiano commented on src/utils/Splinter.js
>                  console.log("Houston, we have a problem!");
that was there more for me to flag the fact that I had a node that should've been proxied by another but I cannot find its parent node to merge this into, so this node would've been floating free in the graph without connections.
We should never enter that code and so far I've never seen that message, in feature/66 I changed to console.error to leave that in console in case it happens.

2021-08-13 14:13 UTC, ddelpiano commented on src/utils/Splinter.js
> +        let protocols = {
done in feature/66

2021-08-13 14:13 UTC, ddelpiano commented on src/utils/Splinter.js
> +        let contributors = {
done in feature/66

2021-08-13 14:14 UTC, ddelpiano commented on src/utils/Splinter.js
> +                console.log("test");
leftover, I cleaned it, done in feature/66

2021-08-13 14:19 UTC, ddelpiano commented on src/utils/nodesFactory.js
> +const Collection = function (node) {
I like the new constructor to be as explicit as possible with the code, no major difference in the implementation and no need to save the context, so will stick to this :)

2021-08-13 14:19 UTC, ddelpiano commented on src/utils/nodesFactory.js
> +        if (node.type === "Collection") {
fixing this in feature/66

2021-08-13 14:19 UTC, ddelpiano commented
closed this in favour of feature/66

2021-08-13 14:19 UTC, closed without merging